### PR TITLE
add ability to delete notebook

### PR DESCRIPTION
**Pull request by vinmaster**
Add ability to delete notebook from the main page using a trash icon

### CODE REVIEW

**Comment by muety** [comment]
Great contribution, thanks a lot!! :raised_hands: Only thing I don't really like is how many trash bins there are now :thinking: If was thinking more like this: 

image

What do you think?

**Comment by vinmaster** [comment]
Changes are made. Have a look!

**Comment by muety** [comment]
Awesome, thanks! Only one small, last change request: when canceling the password dialog, the DELETE request should also not be executed. 


https://user-images.githubusercontent.com/8978843/195017314-81a98a04-c8fb-4d8a-9e86-c7e8466f5d46.mp4

**Comment by vinmaster** [comment]
Got it, this should fix it. Sorry that I missed that

**Pull request merged**
